{{- if not .Values.rails.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "decidim.fullname" . }}
  labels:
    {{- include "decidim.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.rails.secretKeyBase }}
  SECRET_KEY_BASE: {{ .Values.rails.secretKeyBase | b64enc | quote }}
  {{- else }}
  SECRET_KEY_BASE: {{ randAlphaNum 128 | b64enc | quote }}
  {{- end }}
  {{- if .Values.database.password }}
  DATABASE_PASSWORD: {{ .Values.database.password | b64enc | quote }}
  {{- end }}
{{- end }}
